### ISSUE TITLE
Uncaught TypeError: Router.run is not a function

### ISSUE THREAD

**Issue by askl56** [tylermcginnis/github-notetaker-egghead#23]
I'm guessing this is because this tutorial is out of date?

**Comment by tylermcginnis** [comment]
Yes, unfortunately. See [HERE](https://github.com/tylermcginnis/github-notetaker-egghead/blob/master/app/App.js) for the updated code.

**Comment by askl56** [comment]
Is there an updated tutorial for this?

**Comment by tylermcginnis** [comment]
Just the change logs on the repo. Videos should be updated in the next ~Month.
