### ISSUE TITLE
Route not updating the Profile state

### ISSUE THREAD

**Issue by magalhini** [tylermcginnis/github-notetaker-egghead#3]
I'm still unsure if this is fixed in future lessons, but I've taken a look a bit far ahead in the series and couldn't see this being fixed, so I thought I might as well report it :)

Basically, when manually changing a route (say from /tyler to /anotheruser), all the state is never updated in the UI, because obviously the component itself never updates. The `render` method gets called, it correctly renders the new username, but no trigger is made to fetch the new date from Firebase related to that user.

Only a hard refresh takes care of this. What would be the most efficient way of correcting this?

**Comment by tylermcginnis** [comment]
This is fixed in a later lesson with componentShouldUpdate. Also, definitely didn't see this until now. Sorry for answering this in December when you asked it in July... :see_no_evil:

**Comment by magalhini** [comment]
@tylermcginnis Better late than never :grimacing: I figured it out a few days later anyway and should have remembered to update this thread anyway. Thanks!
