### ISSUE TITLE
ReactFire v 0.5.0 has breaking changes due to array handling in React itself

### ISSUE THREAD

**Issue by rstormsf** [tylermcginnis/github-notetaker-egghead#5]
Regarding branch - 05 - reactfire step

https://jsfiddle.net/yak1xxu3/1/

Already being discussed and files as not a bug

https://github.com/firebase/reactfire/issues/52

Please mention in comments or somewhere if folks will use 0.5.0 ReactFire mixin it's not going to work

**Comment by tylermcginnis** [comment]
Closing because all videos and branches have been updated.

**Comment by rstormsf** [comment]
Thanks! :+1:
