### ISSUE TITLE
Filename typo for section 11. 'seperator.js' should be 'separator.js'

### ISSUE THREAD

**Issue by RTakes** [tylermcginnis/github-notetaker-egghead#9]
Profile.js requires 'separator.js' but the file is named 'seperator.js'.  Throws an error.

https://github.com/eggheadio/react-native-gh-notetaker/blob/11-creating-separator-component/App/Components/Profile.js#L3

https://github.com/eggheadio/react-native-gh-notetaker/tree/11-creating-separator-component/App/Components/Helpers

**Comment by tylermcginnis** [comment]
:see_no_evil: You should make a PR :)
